services:
  app:
    build: ./frontend/
    container_name: frontend
    restart: always
    environment:
      REACT_APP_BASE_URL: http://www.techprodevops.com:5000/
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  db:
    build: ./postgres/
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: "Pp123456789"
    ports:
      - "5432:5432"
    volumes:
      - /db-data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: ./backend/
    container_name: backend
    restart: always
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    container_name: nginx-container
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
